# Generated by Django 5.1.2 on 2024-11-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alert_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='max_temperature_alert',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='preference',
            name='min_temperature_alert',
            field=models.FloatField(default=0),
        ),
    ]
