# Generated by Django 5.1.2 on 2024-11-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_preference_max_temperature_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_temp_c', models.FloatField()),
                ('current_condition', models.CharField(max_length=100)),
                ('current_condition_icon', models.URLField()),
                ('current_wind_kph', models.FloatField()),
                ('current_wind_dir', models.CharField(max_length=5)),
                ('current_pressure_mb', models.FloatField()),
                ('current_precip_mm', models.FloatField()),
                ('current_humidity', models.IntegerField()),
                ('current_cloud', models.IntegerField()),
                ('current_feelslike_c', models.FloatField()),
                ('current_aqi_co', models.FloatField()),
                ('current_aqi_no2', models.FloatField()),
                ('current_aqi_o3', models.FloatField()),
                ('current_aqi_so2', models.FloatField()),
                ('current_aqi_pm2_5', models.FloatField()),
                ('current_aqi_pm10', models.FloatField()),
                ('current_aqi_us_epa_index', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude', 'last_updated'], name='users_weath_latitud_44b76f_idx')],
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temp_c', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('condition_icon', models.URLField()),
                ('wind_kph', models.FloatField()),
                ('wind_dir', models.CharField(max_length=5)),
                ('pressure_mb', models.FloatField()),
                ('precip_mm', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('feelslike_c', models.FloatField()),
                ('chance_of_rain', models.IntegerField()),
                ('weather_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='users.weatherforecast')),
            ],
            options={
                'indexes': [models.Index(fields=['weather_forecast', 'time'], name='users_hourl_weather_6b0618_idx')],
                'unique_together': {('weather_forecast', 'time')},
            },
        ),
    ]
