# Generated by Django 5.1.2 on 2024-11-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_weatherforecast_hourlyforecast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='HourlyForecast',
        ),
        migrations.DeleteModel(
            name='WeatherForecast',
        ),
    ]
