# Generated by Django 5.1.2 on 2024-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_weatherforecast_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='max_temperature_alert',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='min_temperature_alert',
        ),
        migrations.AddField(
            model_name='alert',
            name='max_temp_c',
            field=models.FloatField(default=40, help_text='Set maximum temperature in Celsius.'),
        ),
        migrations.AddField(
            model_name='alert',
            name='min_temp_c',
            field=models.FloatField(default=20, help_text='Set minimum temperature in Celsius.'),
        ),
        migrations.AddField(
            model_name='alert',
            name='rain_probability',
            field=models.FloatField(default=50, help_text='Set rain probability in percentage.'),
        ),
    ]
