# Generated by Django 5.1.2 on 2024-11-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_alert_message_alter_alert_rain_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='max_temp_c',
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name='alert',
            name='min_temp_c',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='rain_probability',
            field=models.FloatField(default=70),
        ),
    ]
